### ISSUE TITLE
User Story: selectable preset palettes for colour-blindness

### ISSUE THREAD

**Issue by TrevorJamesLeslie** [ShaneByrne0963/hackathon-nov-2024#49]
# As a colour-blind user, I want the browser extension to have accessible colour schemes so I can clearly distinguish the different UI elements.

## Acceptance Criteria:
- The extension provides a high-contrast colour mode with distinct visual cues beyond just colour
- All color-coded information has alternative non-colour representations
- Users can customize colours and themes to their preferences

## Tasks:
- [ ] Implement a high-contrast mode with clear visual distinctions beyond colour
- [ ] include a 4-way radio button selector, allowing users to choose quickly & easily choose between normal, protanopia, deuteranopia, and tritanopia modes
- [ ] Ensure color-coded UI has non-colour indicators (icons, labels)
- [ ] Add user settings to customize colours and themes
- [ ] Test with participants who have various colour vision deficiencies

**Comment by TrevorJamesLeslie** [comment]
# As a user, I want to...

## Acceptance Criteria:
- Bullet

## Tasks:
- [ ] tick1
- [ ] tick2 
- [ ] tick3
